# Generated by Django 4.2.9 on 2024-08-15 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quest',
            name='game',
        ),
        migrations.RemoveField(
            model_name='quest',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='quest',
            name='visible',
        ),
        migrations.RemoveField(
            model_name='character',
            name='game',
        ),
        migrations.DeleteModel(
            name='Game',
        ),
        migrations.DeleteModel(
            name='Quest',
        ),
    ]
