# Generated by Django 4.2.9 on 2024-06-06 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_character_player_alter_game_dm_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Quest',
        ),
    ]
