# Generated by Django 4.2.9 on 2024-08-21 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_remove_quest_game_remove_quest_tenant_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Character',
        ),
    ]
